DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    email VARCHAR(254) UNIQUE NOT NULL,
    name  VARCHAR(250)        NOT NULL
);